image:
  repository: 139294524816.dkr.ecr.ap-southeast-2.amazonaws.com/demo-node-app
  tag: staging
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
containerPort: 3000
ingress:
  enabled: true
  className: alb
  host: demo-node-app-eks.aws.deanlofts.xyz
externalSecrets:
  enabled: true
  targetSecretName: demo-node-app-env
  storeRef:
    kind: ClusterSecretStore
    name: aws-parameterstore
  dataFrom:
    - extract:
        key: /devops-refresher/staging/app
env:
  - name: DEPLOY_PLATFORM
    value: eks
