replicaCount: 1

image:
  repository: public.ecr.aws/docker/library/nginx
  tag: "stable"
  # Optional: if set, image will be pulled as "<repository>@<digest>"
  digest: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80

# Container port exposed by the app
containerPort: 80

ingress:
  enabled: false
  className: ""
  host: ""
  # Optional: pass through extra annotations (e.g., ALB config)
  annotations: {}
  # Optional: ACM cert ARN for ALB (sets certificate-arn annotation when provided)
  certificateArn: ""

resources: {}

nodeSelector: {}
affinity: {}
tolerations: []

# Explicit env vars (used when externalSecrets.enabled=false)
env: []
# - name: LOG_LEVEL
#   value: info

# Optional: reference an existing Secret to envFrom
envSecretName: ""

# External Secrets Operator integration
externalSecrets:
  enabled: false
  # Name of the Secret ESO will create and the Deployment will envFrom
  targetSecretName: demo-app-env
  refreshInterval: 1h
  # Reference an existing ClusterSecretStore or SecretStore
  storeRef:
    kind: ClusterSecretStore
    name: aws-parameterstore
  # Pull a whole prefix from SSM/Secrets Manager
  dataFrom: []
  #   - extract:
  #       key: /devops-refresher/staging/app
  # Pull specific keys
  data: []
  #   - secretKey: DB_PASS
  #     remoteRef:
  #       key: /devops-refresher/staging/app/DB_PASS

# Optional build version to force rollouts even when tag is unchanged
# If set, it is added as a pod-template annotation: rollme/buildVersion
buildVersion: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
