{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "demo-app.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "demo-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
{{- with .Values.serviceAccount.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}

