version: 0.2
phases:
  install:
    commands:
      - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl && mv kubectl /usr/local/bin/
      - curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  pre_build:
    commands:
      - IMAGE_URI=$(cat image_uri.txt)
      - echo Using image $IMAGE_URI
      - aws eks update-kubeconfig --name $EKS_CLUSTER --region $AWS_DEFAULT_REGION
  build:
    commands:
      - helm upgrade --install demo-app chart/ \
        --namespace demo --create-namespace \
        --set image.repository=${IMAGE_URI%:*} \
        --set image.tag=${IMAGE_URI##*:} \
        --set service.port=$SERVICE_PORT \
        --set ingress.host=$INGRESS_HOST
artifacts:
  files: []
